### ISSUE TITLE
Вставка виджета прямо в текст страницы

### ISSUE THREAD

**Issue by kvalood** [imagecms/ImageCMS#105]
Собственно вопрос, как вывести виджет или подключить *.tpl прямо в тексте страницы?

Допустим в шаблонах работает функция {include_tpl('comments_list')}, а в тексте страницы нет.

**Comment by cms-admin** [comment]
Напишите регулярное выражение, которое будет обрабатывать текст страницы, например $page.full_text, и рендерить виджет, если найдет шорткод для него.

**Comment by kvalood** [comment]
Да, так и сделал. Сначала не додумался :)
Написал на скорую руку - [https://docs.google.com/document/d/1FacRvDXOQZMSl0V96AKZTodAQivqvn7ygYaFYhUQmnE/edit#heading=h.yoylexnl7zpv](url)
