### ISSUE TITLE
Юзабилити шапки админки

### ISSUE THREAD

**Issue by skive** [imagecms/ImageCMS#58]
Предлагаю сделать шапку админки более компактной и удобной:

1) Интегрировать элементы шапки в меню как на картинке
2) Поднять меню к самому верху страницы

![GitHub Logo](http://i.minus.com/ibpavRYO87coiP.jpg)

**Comment by koloda** [comment]
Об этом можно подумать, но только в базовой версии. В Shop такого сделать не получится из-за наличия дополнительных элементов управления.

**Comment by imagecms** [comment]
обсуждаем на idea.imagecms.net
