### ISSUE TITLE
Хук admin_tpl_edit_page

### ISSUE THREAD

**Issue by skive** [imagecms/ImageCMS#60]
В версии 4.0 из шаблона в файлах add_page.tpl и edit_page.tpl пропал хук admin_tpl_edit_page. Ранее он использовался модулем доп. полей, сейчас модуль вставлен в код шаблона - что само по себе не комильфо. 

Проблема с хуком понятна - ранее можно было добавлять таб и его содержимое в одном месте из одного хука, теперь заголовки табов и их содержимое находятся в разных местах шаблона. 

Однако решение проблемы есть - нужно вернуть хук туда, где он стоял в шаблоне версии 3.х. Добавление нового таба в этом случае будет происходить с помощью простого кода Javascript:

``` html
<div class="tab-pane" id="sample_tab"></div>
<script type="text/javascript">
    $().ready(function(){
        $("#tabs-page-settings").append('<a href="#sample_tab" class="btn btn-small">Новый таб</a>');
            ajax_div("sample_tab", base_url + "admin/components/cp/attachments/sample_module/" + '.$update_page_id.');
    });
</script>
```

Таким образом таб будет создаваться динамически, а загрузка его содержимого будет происходить с помощью ajax.
Можно пойти дальше и создать в cms функцию на javascript, которая будет добавлять таб с содержимым (принимая два параметра - название таба и содержимое).

**Comment by imagecms** [comment]
Использовали вместо хуков систему событий ImageCMS. Ознакомится можно здесь http://idea.imagecms.net/topic/163721-cmsfactoryevents-class/
