### ISSUE TITLE
Не работает jQuery в админках модулей

### ISSUE THREAD

**Issue by skive** [imagecms/ImageCMS#62]
Возможно, из-за того, что JS (в том числе JQuery) подключаются в конце документа, при загрузке админок модулей в их коде не видно JQuery:
`[21:29:02.613] ReferenceError: $ is not defined`

**Comment by skive** [comment]
Копание проблемы выявило возможную взаимосвязь с проверкой прав, которая выдает ошибку доступа вместе с html кодом модуля по ajax...

**Comment by ymamonchuk** [comment]
Спасибо, исправили.
