### ISSUE TITLE
Хлебные крошки

### ISSUE THREAD

**Issue by kvalood** [imagecms/ImageCMS#98]
При подключении хлебных крошек в файле main.tpl - все ОК.
Но если мы их подключаем например в **page_full.tpl** - хлебные крошки пустые. 

Так стало после обновления 4.12

p.s. Хлебные крошки подключаются через 
`{widget('breadcrumbs')}`

**Comment by kvalood** [comment]
Проверил на чистой версии 4.11 - все нормально работает.

Не знаю почему, но когда хлебные крошки загружаются не из main.tpl, но переменная `$this->core->cat_content;` пустая

**Comment by StanislavKnysh** [comment]
Собственно в чем вопрос? 
Если есть стандартные хлебные крошки в странице page_full.tpl
http://pix.toile-libre.org/upload/original/1478702784.png
Если вы используете на Corporate, не могли бы точней описать суть проблемы

**Comment by kvalood** [comment]
Не вопрос, а проблема.
Прочитайте внимательно первые 2 предложения. 

Речь идет именно про Corporate версию, shop версией не пользуюсь.

Вот скрины: 
https://s.mail.ru/DHjz/URh8pg5qg
https://s.mail.ru/4UYG/zhQHdrkd1

**Comment by StanislavKnysh** [comment]
`/application/modules/core/src/Controller/PageController.php
`

`$this->ci->core->page_content = $page;
  $this->ci->core->cat_content = $category;`
перенесите над 
        `$this->ci->template->assign('content', $this->ci->template->read($pageTemplate));`

**Comment by kvalood** [comment]
Как я этого не доглядел, около часа провозился и не нашел ошибки.
Сделайте правки в коде CMS. 

Это как ни как ошибочка...
